include:
  - "demo/**"
  - "pilot_app/**"
  - "config.yml"
exclude:
  - "demo/target/generated-sources/**"
  - "pilot_app/**/*.g.dart"
backup_dir: ".backups"
backup_retention_days: 7
generated_openapi: "demo/openapi.yaml"
