services:
  mock_api:
    image: clue/json-server
    environment:
      - JSON_SERVER_DATA=/data/db.json
      - JSON_SERVER_PORT=80
      - JSON_SERVER_HOST=0.0.0.0
    volumes:
      - ./pilot_app/mock-data:/data
    ports:
      - "3000:80"
