services:
  backend:
    build:
      context: ./demo
    container_name: demo-backend
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: dev
    depends_on:
      - mock_api
    networks:
      - app-net

  mock_api:
    image: clue/json-server
    container_name: mock-api
    environment:
      - JSON_SERVER_DATA=/data/db.json
      - JSON_SERVER_PORT=80
      - JSON_SERVER_HOST=0.0.0.0
    volumes:
      - ./pilot_app/mock-data:/data
    ports:
      - "3000:80"
    networks:
      - app-net

  # ───────── PostgreSQL (اختياري — فعّل عند الحاجة) ─────────
  # postgres:
  #   image: postgres:16
  #   container_name: demo-postgres
  #   environment:
  #     POSTGRES_USER: demo
  #     POSTGRES_PASSWORD: demo
  #     POSTGRES_DB: demo
  #   ports:
  #     - "5432:5432"
  #   networks:
  #     - app-net

networks:
  app-net:
    driver: bridge
