/* =======================================================================
   V1__init.sql
   تهيئة المخطط الأساسي للتطبيق
   ينشئ جدول BOOKINGS المتوافق مع الكيان BookingEntity
   ======================================================================= */

CREATE TABLE bookings (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    flight_id     VARCHAR(50)  NOT NULL,
    user_id       VARCHAR(50)  NOT NULL,
    seat_count    INTEGER      NOT NULL,
    status        VARCHAR(20)  NOT NULL,
    booking_time  TIMESTAMP WITH TIME ZONE NOT NULL
);

/* فهارس مساعدة للاستعلامات الشائعة */
CREATE INDEX idx_bookings_flight ON bookings (flight_id);
CREATE INDEX idx_bookings_user   ON bookings (user_id);
