openapi: 3.0.1
info:
  title: Demo API
  version: 0.0.1
  description: التعريف الموحد لواجهة برمجة التطبيقات

servers:
  - url: http://localhost:8080
    description: Local server

paths:
  /users:
    get:
      summary: استرجاع جميع المستخدمين
      operationId: getUsers
      responses:
        '200':
          description: قائمة المستخدمين
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/UserDTO'
    post:
      summary: إنشاء مستخدم جديد
      operationId: createUser
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserDTO'
      responses:
        '201':
          description: المستخدم الذي تم إنشاؤه
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserDTO'

components:
  schemas:
    UserDTO:
      type: object
      properties:
        id:
          type: integer
          example: 1
        name:
          type: string
          example: "Hector Jackson"
        email:
          type: string
          format: email
          example: "hector@example.com"
